# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 09:21
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('micasa', '0002_remove_hood_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pic',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
